version: '3.8'
name: fundamentos-spark-cluster

services:
  spark-master:
    container_name: fundamentos-spark-master
    build: .
    image: fundamentos-spark-image
    entrypoint: ['./entrypoint.sh', 'master']
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080" ]
      interval: 5s
      timeout: 3s
      retries: 3
    volumes:
      - ../:/workspace
      - spark-logs:/opt/spark/spark-events
      - ./spark-events:/opt/spark/spark-events
    env_file:
      - .env.spark
    ports:
      - '9091:8080'
      - '7071:7077'

  spark-history-server:
    container_name: fundamentos-spark-history
    image: fundamentos-spark-image
    entrypoint: ['./entrypoint.sh', 'history']
    depends_on:
      - spark-master
    env_file:
      - .env.spark
    volumes:
      - spark-logs:/opt/spark/spark-events
    ports:
      - '18081:18080'

volumes:
  spark-logs: